# 🐼 Pandas I: Fundamentos y Manipulación de Datos

Esta sesión está pensada para un grupo con ritmo ágil.

## Objetivo
Pasar de archivos crudos a un flujo real de trabajo con pandas:
- cargar,
- inspeccionar,
- seleccionar,
- filtrar,
- transformar,
- ordenar,
- exportar.

## Estructura
Vamos a trabajar en bloques cortos de demostración + ejercicio práctico.


In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

np.random.seed(42)


## 1️⃣ Series: la estructura más simple

Una **Series** es un array unidimensional con índice.

Puedes verla como una columna suelta con etiquetas.


In [2]:
values = [10, 20, 30, 40]
s_list = pd.Series(values, index=['a', 'b', 'c', 'd'])

data_dict = {'Apple': 100, 'Banana': 200, 'Cherry': 150}
s_dict = pd.Series(data_dict)

print("Series from list:", s_list)
print()
print("Series from dict:", s_dict)
print()
print("Index:", s_dict.index)
print("Values:", s_dict.values)


Series from list: a    10
b    20
c    30
d    40
dtype: int64

Series from dict: Apple     100
Banana    200
Cherry    150
dtype: int64

Index: Index(['Apple', 'Banana', 'Cherry'], dtype='str')
Values: [100 200 150]


### 🧠 Ejercicio 1: crea e inspecciona una Series

1. Crea una Series llamada `temperatures` con los valores `18, 21, 19, 24`.
2. Usa como índice `"Mon", "Tue", "Wed", "Thu"`.
3. Muestra el valor de `"Wed"`.
4. Muestra su índice y sus valores.


In [9]:
# Version 1
temperaturas1 = pd.Series([18, 21, 19, 24], ["Mon", "Tue", "Wed", "Thu"])
print("Serie1",temperaturas1)
print("Valor de Wed: ", temperaturas1["Wed"])
print("Indices: ",temperaturas1.index)
print("Valores: ",temperaturas1.values)

#Version B
dict = {"Mon":18, "Tue":21, "Wed":19,"Thu":24}
temperaturas2 = pd.Series(dict)
print("Serie2:",temperaturas2)




Serie1 Mon    18
Tue    21
Wed    19
Thu    24
dtype: int64
Valor de Wed:  19
Indices:  Index(['Mon', 'Tue', 'Wed', 'Thu'], dtype='str')
Valores:  [18 21 19 24]
Serie2: Mon    18
Tue    21
Wed    19
Thu    24
dtype: int64


## 2️⃣ DataFrames: la tabla de datos

Un **DataFrame** es una estructura bidimensional con filas y columnas.

Normalmente se crea a partir de un diccionario de listas.


In [10]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Paris', 'London', 'Tokyo'],
    'Salary': [50000, 60000, 70000, 80000],
}

df_manual = pd.DataFrame(data)
display(df_manual)
print("Shape:", df_manual.shape)


,Name,Age,City,Salary
0,Alice,25,New York,50000
1,Bob,30,Paris,60000
2,Charlie,35,London,70000
3,David,40,Tokyo,80000


Shape: (4, 4)


### 🧠 Ejercicio 2: crea un DataFrame manualmente

Crea un DataFrame llamado `df_products` con estas columnas:
- `Product`
- `Price`
- `Stock`

Usa al menos 4 filas.

Después:
1. muéstralo,
2. imprime `shape`,
3. imprime solo los nombres de columnas.


In [13]:
# Your code here
data = {
    'Product': ['Phone', 'Laptop', 'Teclado', 'Mouse'],
    'Price': [25, 30, 35, 40],
    'Stock': [50, 40, 70,90],
}

df_productos = pd.DataFrame(data)
display(df_productos)
display(df_productos.shape)
display(df_productos.columns)

,Product,Price,Stock
0,Phone,25,50
1,Laptop,30,40
2,Teclado,35,70
3,Mouse,40,90


(4, 3)

Index(['Product', 'Price', 'Stock'], dtype='str')

## 3️⃣ Lectura de archivos con pandas

Aquí es donde pandas empieza a ahorrar muchísimo tiempo.

Hoy vamos a cargar:
- CSV,
- JSON simple,
- JSON con lista de registros,
- Excel.(pip install openpyxl)


In [15]:
df_csv = pd.read_csv('personas.csv')
df_json_list = pd.read_json('personas.json')
df_json_single = pd.read_json('persona.json')

print("CSV loaded:")
display(df_csv)
print("JSON list loaded:")
display(df_json_list)
print("JSON single object loaded:")
display(df_json_single)

try:
    df_excel = pd.read_excel('Book1.xlsx')
    print("Excel loaded:")
    display(df_excel.head())
except Exception as exc:
    print("Excel could not be loaded:", exc)


CSV loaded:


,Nombre,Edad,Ciudad
0,Ana,25,Lima
1,Luis,30,Bogotá
2,María,22,Buenos Aires


JSON list loaded:


,nombre,edad,intereses
0,Ana,25,"[lectura, programación]"
1,Luis,30,"[deportes, música]"
2,María,22,"[arte, cine]"


JSON single object loaded:


,nombre,edad,intereses
0,Ana,25,lectura
1,Ana,25,programación


Excel loaded:


,nombre,edad,altura
0,Alex,25,180
1,Alonso,26,187
2,María,24,175
3,Paula,23,160


### 🧠 Ejercicio 3: carga y compara formatos

1. Carga `personas.csv` en un DataFrame llamado `people_csv`.
2. Carga `personas.json` en un DataFrame llamado `people_json`.
3. Muestra `shape` de ambos.
4. Muestra las 2 primeras filas de cada uno.


In [ ]:
# Ejercicio 3
people_csv = pd.read_csv('personas.csv')
print(people_csv.shape)
print(people_csv.head(2))

people_json = pd.read_json('personas.json')
print(people_json.shape)
print(people_json.head(2))


(3, 3)
  Nombre  Edad  Ciudad
0    Ana    25    Lima
1   Luis    30  Bogotá
(3, 3)
  nombre  edad                intereses
0    Ana    25  [lectura, programación]
1   Luis    30       [deportes, música]


## 4️⃣ Inspección: mirar antes de tocar

Antes de hacer análisis o limpieza, hay que responder rápido:
- ¿cuántas filas y columnas hay?
- ¿qué tipos tengo?
- ¿qué aspecto tienen los datos?


In [22]:
nampy_array =  np.random.randint(0, 100, size=(100, 5))
print("Numpy array: ", nampy_array[:10])

df_large = pd.DataFrame(
    np.random.randint(0, 100, size=(100, 5)),
    columns=['A', 'B', 'C', 'D', 'E']
)

display("Df head: ",df_large.head(3))
display("Df tail: ",df_large.tail(3))

print("Shape:", df_large.shape)
print("Rows:", df_large.shape[0])
print("Columns:", df_large.shape[1])

print("df_large.info")
df_large.info()
print("df_large.describe")
display(df_large.describe())


Numpy array:  [[53 20 73 37 45]
 [ 3 59 56 44 19]
 [16 70  3 92 13]
 [ 2 87 79 57 54]
 [ 3 23 33 29 81]
 [18 30 59 59 18]
 [48 62 82 21 23]
 [75 29 57 30 99]
 [63 18 47 44 99]
 [93 54 54 96 17]]


'Df head: '

,A,B,C,D,E
0,10,63,49,84,20
1,68,47,19,66,43
2,32,72,60,8,67


'Df tail: '

,A,B,C,D,E
97,76,44,95,33,44
98,60,82,15,65,39
99,16,33,15,59,65


Shape: (100, 5)
Rows: 100
Columns: 5
df_large.info
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       100 non-null    int32
 1   B       100 non-null    int32
 2   C       100 non-null    int32
 3   D       100 non-null    int32
 4   E       100 non-null    int32
dtypes: int32(5)
memory usage: 2.1 KB
df_large.describe


,A,B,C,D,E
count,100.000000,100.000000,100.000000,100.000000,100.000000
mean,53.020000,46.370000,47.980000,47.860000,45.970000
std,26.944755,29.173343,28.422846,28.074223,24.731061
min,1.000000,0.000000,1.000000,0.000000,0.000000
25%,33.750000,20.750000,22.750000,26.500000,25.750000
50%,56.500000,44.500000,45.500000,49.000000,45.000000
75%,74.000000,71.250000,72.000000,71.250000,63.250000
max,99.000000,97.000000,99.000000,98.000000,99.000000


### 🧠 Ejercicio 4: radiografía rápida del DataFrame

Usando `df_large`:
1. muestra las 5 primeras filas,
2. muestra las 5 últimas,
3. imprime `shape`,
4. imprime solo el número de filas usando `shape[0]`,
5. imprime `dtypes`.


In [ ]:
# Ejercicio 4 
df_large = pd.DataFrame(
    np.random.randint(0, 100, size=(100, 5)),
    columns=['A', 'B', 'C', 'D', 'E']
)

print("Primeras 5 filas", df_large.head(5))
print("Ultimas 5 filas", df_large.tail(5))
print("Shape: ", df_large.shape)
print("Rows: ", df_large.shape[0])

print("Dtypes: \n", df_large.dtypes)

Primeras 5 filas     A   B   C   D   E
0  94  21  65  44  68
1  90  88  71   0  83
2  43  86  95  74  38
3  53  87  74  28  53
4  89  15  98  19  45
Ultimas 5 filas      A   B   C   D   E
95  54  85  84  25  84
96  24  64   5  22  63
97  86  42  22  95  29
98  76  17  86  78  96
99  20  56  22  90  44
Shape:  (100, 5)
Rows:  100
Dtypes: 
 A    int32
B    int32
C    int32
D    int32
E    int32
dtype: object


## 5️⃣ Selección e indexación

Aquí está uno de los núcleos de la clase:
- `df['columna']` para columnas,
- `df[['col1', 'col2']]` para varias columnas,
- `.iloc` por posición,
- `.loc` por etiqueta.


In [ ]:
col_a = df_large['A']
cols_subset = df_large[['A', 'C', 'E']]

display(cols_subset.head(3))
display(df_large.iloc[0:5, 0:3])
display(df_large.loc[0:5, ['A', 'D']])
print("Value at iloc[10, 2]:", df_large.iloc[10, 2])
print("Value at loc[0, 'A']:", df_large.loc[0, 'A'])


### 🧠 Ejercicio 5: selección

Usando `df_large`:
1. selecciona las columnas `B` y `E`,
2. muestra las filas 50 a 55 usando `.iloc`,
3. muestra el valor de la fila `0` y la columna `A` usando `.loc`,
4. selecciona filas 10 a 15 y columnas `C` y `D`.


In [43]:
# Ejercicio 5
df_large = pd.DataFrame(
    np.random.randint(0, 100, size=(100, 5)),
    columns=['A', 'B', 'C', 'D', 'E']
)
print("1-Columnas B y E")
display(df_large[['B', 'E']])
print("2-Filas de la 50-55")
display(df_large.iloc[50:56,0:3])
print("3-Valor de la fila 0 columna A")
display(df_large.loc[0,'A'])

print("4-Fila de la 10-15 y columnas C y D")
display(df_large.loc[10:15,'C':'D'])


1-Columnas B y E


,B,E
0,45,39
1,54,4
2,12,96
3,61,23
4,6,67
...,...,...
95,17,36
96,13,59
97,94,29
98,83,26


2-Filas de la 50-55


,A,B,C
50,69,27,94
51,41,22,69
52,23,16,64
53,59,49,92
54,66,64,26
55,61,43,18


3-Valor de la fila 0 columna A


np.int32(98)

4-Fila de la 10-15 y columnas C y D


,C,D
10,32,99
11,7,27
12,79,73
13,94,77
14,49,16
15,50,63


## ☕ Descanso sugerido (15 min)

Aquí ya deberían saber cargar, inspeccionar y seleccionar.


## 6️⃣ Filtrado y transformación

El patrón más común en trabajo real es:
1. filtrar filas,
2. crear columnas nuevas,
3. volver a filtrar,
4. quedarte solo con lo útil.


In [48]:
mask = df_large['A'] > 50
filtered_df = df_large[mask]
#display(filtered_df)

print("Original rows:", df_large.shape[0])
print("Filtered rows:", filtered_df.shape[0])

complex_filter = df_large[(df_large['A'] > 50) & (df_large['B'] < 20)]
display(complex_filter.head())

df_large['Suma'] = df_large['A'] + df_large['B']
display(df_large.head())


Original rows: 100
Filtered rows: 58


,A,B,C,D,E,Suma
1,79,5,66,40,42,84
6,61,9,12,75,8,70
50,72,2,71,37,67,74
57,58,8,11,40,14,66
59,95,5,52,19,38,100


,A,B,C,D,E,Suma
0,9,98,57,61,84,107
1,79,5,66,40,42,84
2,84,76,17,57,59,160
3,87,26,67,21,23,113
4,39,73,65,39,5,112


### 🧠 Ejercicio 6: máscaras y columnas nuevas

Usando `df_large`:
1. crea una columna `Total_AB` con `A + B`,
2. filtra filas con `A > 50`,
3. filtra filas con `A > 50` y `B < 20`,
4. muestra solo las columnas `A`, `B` y `Total_AB` del resultado filtrado.


In [70]:
# Ejercicio 6
df_large = pd.DataFrame(
    np.random.randint(0, 100, size=(100, 5)),
    columns=['A', 'B', 'C', 'D', 'E']
)
display(df_large)
print("1- Nueva columna Total_AB")
df_large['Total_AB'] = df_large['A'] + df_large['B']

print("2- Fila A>50")
#display(df_large[df_large['A'] > 50])

print("3- Fila A>50 y B<20")
df_large = df_large[(df_large['A'] > 50) & (df_large['B'] < 20)]
display(df_large[['A','B', 'Total_AB']])



,A,B,C,D,E
0,77,35,26,72,54
1,69,94,80,52,59
2,60,35,84,26,40
3,27,15,34,35,55
4,98,18,56,84,32
...,...,...,...,...,...
95,73,68,46,75,95
96,41,30,21,16,83
97,19,7,97,48,86
98,37,52,27,76,28


1- Nueva columna Total_AB
2- Fila A>50
3- Fila A>50 y B<20


,A,B,Total_AB
4,98,18,116
24,56,3,59
27,58,1,59
32,70,17,87
76,79,9,88
89,84,18,102
99,71,10,81


## 7️⃣ Ordenación

Después de seleccionar y filtrar, normalmente queremos ordenar resultados.

Podemos ordenar por una o varias columnas, y decidir el sentido de cada una.


In [ ]:
df_sorted = df_large.sort_values(by='A', ascending=True)
df_multi_sort = df_large.sort_values(by=['A', 'B'], ascending=[False, True])

display(df_sorted.head())
display(df_multi_sort.head())


### 🧠 Ejercicio 7: ordena resultados

1. Ordena `df_large` por la columna `C` de mayor a menor.
2. Ordena `df_large` por `B` descendente y `D` ascendente.
3. Muestra las 5 primeras filas de cada resultado.


In [76]:
# Ejercicio 7
df_large = pd.DataFrame(
    np.random.randint(0, 100, size=(100, 5)),
    columns=['A', 'B', 'C', 'D', 'E']
)

print("1-Order by Column C-DESC")
df_sorted = df_large.sort_values(by='C', ascending=False)
display(df_sorted.head(5))

print("2-Order by Column B-DESC and ColumnD-ASC")
df_sorted = df_large.sort_values(by=['B','D'], ascending=[False,True])
display(df_sorted.head(5))

1-Order by Column C-DESC


,A,B,C,D,E
38,52,47,99,90,85
83,96,21,98,16,85
20,99,61,97,56,94
91,75,34,97,15,35
37,10,74,97,28,61


2-Order by Column B-DESC and ColumnD-ASC


,A,B,C,D,E
2,28,99,60,67,8
46,17,99,35,75,49
74,61,99,59,79,53
39,65,99,47,93,58
59,28,98,83,99,60


## 🏆 Práctica Final

Usando `df_large`:

1. Crea una nueva columna llamada `Suma` que sea `A + B`.
2. Filtra las filas donde `Suma` sea mayor a `100`.
3. Quédate solo con las columnas `A`, `B`, `C` y `Suma`.
4. Ordena el resultado por la columna `C` de forma descendente.
5. Guarda el resultado en un archivo `resultado.csv`.


In [94]:
# Proyecto FInal
df_large = pd.DataFrame(
    np.random.randint(0, 100, size=(100, 5)),
    columns=['A', 'B', 'C', 'D', 'E']
)
print("1- Add column Suma = A+B")
df_large['Suma'] = df_large['A']+df_large['B']
display(df_large.head())

print("2-Filter Suma > 100")
df_large = df_large[df_large['Suma'] > 100]
display(df_large.head())

print("3-Mostrar columnas A,B,C,Suma")
display(df_large[['A','B','C','Suma']])

print("4-Order By Column C - DESC")
df_sorted = df_large.sort_values(by='C', ascending=False)
display(df_sorted.head())

print("5-Save en resultado.csv")
df_sorted.to_csv("resultado.csv", index=False)



1- Add column Suma = A+B


,A,B,C,D,E,Suma
0,31,61,90,97,44,92
1,48,32,3,17,69,80
2,63,27,57,90,89,90
3,55,19,76,91,33,74
4,86,9,93,21,4,95


2-Filter Suma > 100


,A,B,C,D,E,Suma
6,64,97,40,63,54,161
7,89,17,15,86,45,106
8,35,89,65,43,4,124
10,71,84,7,51,68,155
14,84,47,45,45,47,131


3-Mostrar columnas A,B,C,Suma


,A,B,C,Suma
6,64,97,40,161
7,89,17,15,106
8,35,89,65,124
10,71,84,7,155
14,84,47,45,131
16,18,90,41,108
18,87,61,92,148
19,86,26,41,112
21,84,82,88,166
24,80,76,28,156


4-Order By Column C - DESC


,A,B,C,D,E,Suma
27,60,90,99,81,94,150
97,88,67,98,40,49,155
67,27,76,96,2,62,103
40,49,80,95,0,90,129
60,71,89,95,27,95,160


5-Save en resultado.csv
