# Introducción a NumPy

## ¿Qué es NumPy?

NumPy (Numerical Python) es una librería fundamental para la computación científica con Python. Nos permite trabajar de manera eficiente con **arreglos** (arrays) y **matrices** (arrays multidimensionales) que ofrecen gran rapidez y flexibilidad en el manejo de datos numéricos.

## ¿Por qué es útil?

- **Arreglos eficientes**: NumPy está optimizado para realizar operaciones sobre arreglos de gran tamaño de forma muy rápida.
- **Herramientas matemáticas**: Incluye muchas funciones matemáticas (álgebra lineal, transformadas de Fourier, estadísticas, etc.).
- **Base para otras librerías**: Librerías importantes en Inteligencia Artificial y Data Science (como Pandas, TensorFlow, PyTorch y scikit-learn) usan NumPy en su núcleo.
- **Operaciones vectorizadas**: Permite realizar operaciones sobre conjuntos de datos completos sin necesidad de bucles explícitos en Python, lo que facilita y acelera el desarrollo de experimentos y prototipos.

## ¿Qué es un array de NumPy?

Un **array** de NumPy (o `ndarray`) es una estructura de datos que contiene valores de un mismo tipo (generalmente numéricos) y que se organiza en uno o más **dimensiones**. 

Ejemplos:
- Un array unidimensional (similar a una lista)
- Un array bidimensional (matriz)
- Un array de más dimensiones (3D, 4D, etc.)

Esta estructura permite indexación y slicing de manera muy eficiente.

---

## 1️⃣ La Prueba de Velocidad
Vamos a comprobar empíricamente por qué usamos NumPy. Elevaremos al cuadrado 1 millón de números y compararemos el tiempo con una lista estándar de Python.

In [1]:
import numpy as np

# Data preparation: 1 million elements
python_list = list(range(1_000_000))
numpy_array = np.arange(1_000_000)

print("--- Time with Python Lists ---")
%timeit [x**2 for x in python_list]

print("\n--- Time with NumPy ---")
%timeit numpy_array**2

--- Time with Python Lists ---
52.6 ms ± 2.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

--- Time with NumPy ---
2.03 ms ± 213 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


---

## 2️⃣ Creación de Arrays

Raramente escribiremos los arrays a mano `[1, 2, 3]`. Usaremos generadores automáticos.

In [25]:
# 1. From a list (basic)
arr = np.array([1, 2, 3])

# 2. Numerical ranges
rng = np.arange(0, 10, 2)  # From 0 to 10, step 2
lin = np.linspace(0, 1, 5) # 5 equidistant points between 0 and 1

# 3. Filler arrays (useful for initializing weights or empty images)
zeros = np.zeros((3, 3))     # 3x3 matrix of zeros
ones = np.ones((2, 4))       # 2x4 matrix of ones
identity = np.eye(4)         # Identity matrix
full = np.full((2, 2), 7)    # Matrix filled with specific value (7)

# 4. Random values (simulation)
random_floats = np.random.rand(3, 2)  # 3 rows, 2 cols (0 to 1)
random_ints = np.random.randint(0, 100, size=(5,)) # 5 ints from 0 to 99

print("Range:", rng)
print("\nLinspace:", lin)
print("\nRandom Floats:\n", random_floats)

Range: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]

Random Floats:
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]


### Atributos clave
Es vital inspeccionar un array antes de trabajar con él para entender sus dimensiones.

In [ ]:
tensor = np.zeros((3, 4, 2))

print("Shape:", tensor.shape) # (3 layers, 4 rows, 2 cols)
print("Ndim:", tensor.ndim)
print("Size:", tensor.size)
print("Dtype:", tensor.dtype)

### ⚡ Ejercicio 1: El Arquitecto de Matrices
1. Crea un array con los números pares del 10 al 50.
2. Crea una matriz de 4x4 llena solo del número 5.
3. Crea una Matriz Identidad de 5x5.
4. Crea un array de 5 valores equidistantes entre 0 y 100.

In [ ]:
# Your code here

# 1. Even numbers from 10 to 50 (50 included, so we stop at 51)
evens = np.arange(10, 51, 2)
print("1. Evens:", evens)


# 2. 4x4 Matrix filled with 5
matrix_fives1 = np.full((4, 4), 5) # Option A: Using np.full
print("\n2. Matrix of 5s Opcion A con full:\n", matrix_fives1)

matrix_fives2 = np.ones((4, 4)) * 5 # Option B: Using np.ones * 5
print("\n2. Matrix of 5s Opcion B con ones:\n", matrix_fives2)


# 3. Identity Matrix 5x5
identity = np.eye(5)
print("\n3. Identity:\n", identity)

# 4. Linspace (0 to 100, 5 points)
points = np.linspace(0, 100, 5)
print("\n4. Linspace:", points)


1. Evens: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

2. Matrix of 5s Opcion A con full:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

2. Matrix of 5s Opcion B con ones:
 [[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]

3. Identity:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

4. Linspace: [  0.  25.  50.  75. 100.]


---

## 3️⃣ Indexación y Slicing (Accediendo a los datos)

En NumPy, accedemos a las coordenadas mediante `[fila, columna]`.

**Regla de oro:** `array[start:stop:step]`

In [ ]:
matrix = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# Specific element
print("Element at row 1, col 2:", matrix[1, 2])  # 70

# Slicing: Extract sub-regions
# [rows, columns]
print("\nFirst 2 rows, cols 1 to 3:")
print(matrix[:2, 1:3])

# Extract full column (common in ML for features)
print("\nLast column:", matrix[:, -1])

# Advanced Indexing (Fancy Indexing)
# Getting rows 0 and 2
print("\nRows 0 and 2:\n", matrix[[0, 2], :])

### Indexación Booleana (Filtros)
Podemos usar condiciones lógicas para filtrar datos. Esto devuelve una máscara de Verdadero/Falso (True/False).

In [ ]:
data = np.array([5, 10, 15, 20, 25])

# Logical condition
mask = data > 12
print("Mask:", mask)

# Apply mask
filtered_data = data[mask]
print("Filtered:", filtered_data)

# One-liner (Common usage)
print("Evens:", data[data % 2 == 0])

In [ ]:
my_list = list(range(5,26,5))

my_list_filtered = []
for x in my_list:
    if x > 12:
        my_list_filtered.append(x)

my_list_filtered2 = [x for x in my_list if x > 12]

print("Filtered with loop:", my_list_filtered)
print("Filtered with list comprehension:", my_list_filtered2)




In [ ]:
my_array = np.array(["pepe", "juan", "maria"])
print(my_array[np.char.startswith(my_array, 'j')])
my_list = ["pepe", "juan", "maria"]

result = []

for name in my_list:
    if name.startswith('j'):
        result.append(name)
print(result)

### ⚡ Ejercicio 2: Análisis de Ventas
Tienes un array de ventas diarias: `sales = np.array([100, 250, 90, 300, 500, 45])`.

1. Extrae las ventas del día 2 al día 4.
2. Encuentra qué días (los valores) superaron los 200€.
3. Extrae los valores de ventas de las posiciones pares (índices 0, 2, 4...).

In [18]:
sales = np.array([100, 250, 90, 300, 500, 45])

# 1- Extrae ventas del 1 al 4

ventas = sales[1:4]
print(ventas)

# 2- Encuentra qué días (los valores) superaron los 200€.
print("Ventas > 200: ", sales[sales > 200])

# 3- Extrae los valores de ventas de las posiciones pares (índices 0, 2, 4...)
print("Ventas de las posiciones pares: ")
#Version A
print("Version A- Usando Slicing con step 2:", sales[::2])
# Version B
indices = np.arange(0, len(sales), 2)
print("Version B- Usando filtrado booleano:", sales[indices])
#Version C
indice = np.arange(len(sales))
even_days_alt = sales[indice % 2 == 0]
print("Version C- Usando filtrado booleano:", even_days_alt)

#Resumen 
#[1:4]	--> slicing
#[sales > 200]	--> filtrado booleano
#[::2]	--> slicing con saltos
#sales[inicio : fin] Incluye el índice inicial, Excluye el índice final
#sales[inicio : fin : salto] desde el inicio, hasta el final, saltando de 2 en 2



[250  90 300]
Ventas > 200:  [250 300 500]
Ventas de las posiciones pares: 
Version A- Usando Slicing con step 2: [100  90 500]
Version B- Usando filtrado booleano: [100  90 500]
Version C- Usando filtrado booleano: [100  90 500]


---

## 4️⃣ Vectorización y Operaciones

**Concepto Clave:** En NumPy **NO usamos bucles `for`** para operar sobre datos. Aplicamos la operación directamente al array y NumPy se encarga del resto (Vectorización).

In [ ]:
arr = np.array([1, 2, 3, 4])

print("Add 10:", arr + 10)
print("Multiply:", arr * 2)
print("Square:", arr ** 2)

# Universal Functions (ufuncs)
print("Sqrt:", np.sqrt(arr))
print("Log:", np.log(arr))
print("Exp:", np.exp(arr))

### Caso de Uso Real: Normalización de Datos
En IA, a menudo necesitamos que nuestros datos estén entre 0 y 1. Esto se llama normalización Min-Max.

$$ X_{norm} = \frac{X - min}{max - min} $$

In [ ]:
raw_data = np.array([10, 50, 80, 20, 100])

# Vectorized operation in one line
norm_data = (raw_data - raw_data.min()) / (raw_data.max() - raw_data.min())

print("Normalized (0-1):", norm_data)

### Broadcasting (Difusión)
¿Qué pasa si operamos arrays de distinto tamaño? NumPy intenta "estirar" el pequeño para que encaje.

**Reglas del broadcasting:**
1. Si las dimensiones son iguales, todo bien.
2. Si una dimensión es 1, se puede "estirar" (broadcast) para coincidir con la otra.
3. Si son diferentes y ninguna es 1, da error.

In [ ]:
matrix = np.array([[1, 1, 1],
                   [2, 2, 2]])  # Shape (2, 3)
vector = np.array([10, 20, 30]) # Shape (3,)

# The vector is added to BOTH rows (broadcasted)
print("Broadcast Result:\n", matrix + vector)

# Error example: shapes (2,3) and (2,) are incompatible for broadcasting
# vector_wrong = np.array([1, 2])
# print(matrix + vector_wrong) # This would raise ValueError

#NOTA:
# Un vector es básicamente: 👉 una lista de valores en una sola dimensión.
# [10, 20, 30] vector de 1 dimensión y 3 elementos

# Una matriz es: 👉 una tabla de filas y columnas.
# matrix = np.array([[1, 1, 1], [2, 2, 2]]) tiene 2 filas y 3 columnas

### np.where: El "If" vectorizado
Sintaxis: `np.where(condicion, valor_si_verdadero, valor_si_falso)`

In [ ]:
scores = np.array([4.5, 6.0, 3.2, 9.5, 5.0])

# Classify as Pass/Fail on the fly
classification = np.where(scores >= 5, "Pass", "Fail")
print(classification)

### ⚡ Ejercicio 3: ReLU (Rectified Linear Unit)
ReLU es una función de activación fundamental en Deep Learning. Su lógica es simple: **"Si es negativo, devuelve 0. Si es positivo, devuelve el valor"**.

1. Dado `z = np.array([-10, 2, 0, -5, 8])`.
2. Implementa ReLU usando `np.maximum` o `np.where`.
3. Resultado esperado: `[0, 2, 0, 0, 8]`.

In [ ]:
z = np.array([-10, 2, 0, -5, 8])

# Implementa ReLU usando `np.where`.
new_array = np.where(z < 0, 0, z)
print(new_array)
#Implementa ReLU usando `np.maximum`
new_array = np.maximum(0, z)
print(new_array)

#np.maximum(a, b) compara elemento por elemento y se queda con el mayor.

[0 2 0 0 8]


---

## 5️⃣ Manipulación de Matrices y Estadística Avanzada

### Reshape, Flatten y Transpose
Cambiar la forma de los datos es vital para preparar imágenes o tensores para redes neuronales.

In [ ]:
a = np.arange(1, 13) # Vector of 12 elements
print("Original:", a)

# Reshape to 3x4
matrix = a.reshape(3, 4)
print("\nReshape (3x4):\n", matrix)

# Transpose (switch rows and columns)
print("\nTranspose (4x3):\n", matrix.T)

# Flatten back to 1D
flat = matrix.flatten()
print("\nFlatten:", flat)

### Concatenación y División
Unir y separar datasets es una tarea diaria.

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Vertical Stack (add rows)
v_stack = np.vstack((arr1, arr2))
print("Vertical Stack:\n", v_stack)

# Horizontal Stack (add columns) - requires matching dimensions
h_stack = np.hstack((arr1, np.array([[7], [8]])))
print("Horizontal Stack:\n", h_stack)

### Estadística Descriptiva (Agregaciones)
Podemos colapsar dimensiones sumando o promediando.
* `axis=0`: Opera a lo largo de las filas (colapsa hacia abajo -> Resultado: 1 valor por columna).
* `axis=1`: Opera a lo largo de las columnas (colapsa hacia la derecha -> Resultado: 1 valor por fila).

In [ ]:
data = np.array([
    [10, 20],  # Student A
    [30, 40],  # Student B
    [50, 60]   # Student C
])

print("Total Mean:", data.mean())
print("Mean per Student (rows, axis=1):", data.mean(axis=1))
print("Mean per Subject (cols, axis=0):", data.mean(axis=0))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Max Value:", np.max(data))

### Covarianza y Correlación
Esencial para entender cómo se relacionan dos variables.
* **Covarianza:** Indica si varían juntas (signo).
* **Correlación:** Indica la fuerza de la relación (de -1 a 1).

In [ ]:
study_hours = np.array([1, 2, 3, 4, 5])
grades = np.array([2, 4, 6, 8, 10])

covariance = np.cov(study_hours, grades)
print("Covariance Matrix:\n", covariance)

correlation = np.corrcoef(study_hours, grades)
print("Correlation Matrix:\n", correlation) # 1.0 means perfect linear relationship

---

## 6️⃣ Álgebra Lineal: El Motor de la IA

### Multiplicación de Matrices
Hay tres formas principales, y es vital no confundirlas:
1. **`*` (Element-wise):** Multiplica posición por posición.
2. **`np.dot(A, B)`:** Producto escalar tradicional.
3. **`@`:** Operador moderno para producto de matrices (equivalente a dot para 2D).

**Analogía de la Red Neuronal:**
$$ Output = Inputs \cdot Weights + Bias $$
* **Weights:** La importancia de cada ingrediente (input).
* **Bias:** El toque final que siempre se añade.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print("Element-wise (A * B):\n", A * B)
print("\nDot Product (A.dot(B)):\n", A.dot(B))
print("\nMatrix Product (A @ B):\n", A @ B)

## 🏆 Proyecto Final: El Profesor de NumPy

Tienes una matriz de notas `(5 alumnos, 3 asignaturas)`. Los valores son aleatorios entre 0 y 10.

**Tu misión:**
1. Genera la matriz usando `np.random.randint`.
2. Calcula la nota media de cada alumno.
3. Selecciona solo a los alumnos que tengan una media superior a 5.
4. Normaliza toda la matriz de notas para que estén entre 0 y 1.
5. (Extra): Calcula la matriz de correlación entre las asignaturas (columnas) para ver si hay asignaturas correlacionadas (usa Transpose si es necesario).

In [ ]:
# Final Project Code
np.random.seed(42) # For reproducibility

#1- Crear matriz con np.random.randint
notas = random_ints = np.random.randint(0, 10, size=(5,3))
print(notas)

#2- Calcular nota media de cada alumno
print("Mean por estudiantes (cols, axis=1):", notas.mean(axis=1))

#3- Alumnos con media > 5
print("Alumnos con media > 5: ", notas[notas.mean(axis=1) > 5])

#4 - Normaliza toda la matriz de notas para que estén entre 0 y 1.
norm_data = (notas - notas.min()) / (notas.max() - notas.min())
print("Normalizar con 0 y 1:", norm_data)

#5- Calcula la matriz de correlación entre las asignaturas (columnas) para ver si hay asignaturas correlacionadas 
# Version A
correlation1 = np.corrcoef(notas, rowvar=False)
print("Correlation Matrix:\n", correlation1) # 1.0 means perfect linear relationship

#Version B usando Transpose
correlation2 = np.corrcoef(notas.T)
print("Correlation Matrix:\n", correlation2)# 1.0 means perfect linear relationship


[[6 3 7]
 [4 6 9]
 [2 6 7]
 [4 3 7]
 [7 2 5]]
Mean por estudiantes (cols, axis=1): [5.33333333 6.33333333 5.         4.66666667 4.66666667]
Alumnos con media > 5:  [[6 3 7]
 [4 6 9]]
Normalizar con 0 y 1: [[0.57142857 0.14285714 0.71428571]
 [0.28571429 0.57142857 1.        ]
 [0.         0.57142857 0.71428571]
 [0.28571429 0.14285714 0.71428571]
 [0.71428571 0.         0.42857143]]
Correlation Matrix:
 [[ 1.         -0.82261275 -0.54410719]
 [-0.82261275  1.          0.75592895]
 [-0.54410719  0.75592895  1.        ]]
Correlation Matrix:
 [[ 1.         -0.82261275 -0.54410719]
 [-0.82261275  1.          0.75592895]
 [-0.54410719  0.75592895  1.        ]]
